<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
/* Count for timer calculation declared here */
$count = 1;
$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');

/* Admin Controllers for timer are declared here */
$timer_active = Mage::getStoreConfig('timer/general/activate_magentothem_timer');
$timer_head_active = Mage::getStoreConfig('timer/general/activate_magentothem_heading');
$timer_desc_active = Mage::getStoreConfig('timer/general/activate_magentothem_description');
$timer_color = Mage::getStoreConfig('timer/magentothem_timer_color/text');
$desc_color = Mage::getStoreConfig('timer/magentothem_timer_color/description');
$head_color = Mage::getStoreConfig('timer/magentothem_timer_color/heading_text_color');
$timer_head = Mage::getStoreConfig('timer/general/heading');
$store = Mage::app()->getStore()->getCode();
?>

<script type="text/javascript">
	var j_blog = 1;
</script>
<?php if($this->getConfig('enabled')){ // start enable module?>
	<?php $this->getProducts() ?>
	<?php $_productCollection=$this->getProductCollection() ?>
	<div class="ma-timer-container">
		<?php				
			if ( !$this->getConfig('width_thumbnail') ){
				$w_thumbnail = 135;
			} else {
				$w_thumbnail = $this->getConfig('width_thumbnail');
			}
			if( !$this->getConfig('height_thumbnail') ){
				$h_thumbnail = 135;
			 }
			else {
				$h_thumbnail = $this->getConfig('height_thumbnail');
			}
		?>
		<?php if($this->getConfig('title')){?>
			<div class="ma-timer-title"><h2><?php echo $this->getConfig('title')?></h2></div>
		<?php }?>
		<?php if(!$_productCollection->count()): ?> 
			<div class="ma-timer">	
				<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
			</div>
		<?php else: ?>
			<?php
			$rows = $this->getConfig('row_show');
			?>
				<ul class="bxslider">
					<?php $_collectionSize = $_productCollection->count() ?>
					<?php $i=0; foreach ($_productCollection as $_product): ?>
					<?php $toDate = $_product->getSpecialTODate();?>
					<?php $fromDate = $_product->getSpecialFromDate(); ?>
					<?php if($i %$rows == 0) echo "<li class='timer-item'>"; ?>
								<div class="item-inner">
									
					<div class="product-link">
						<div class="products clearfix">
							<div class="product">
								<div class="images-container">
									<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
										<span class="product-image">
											<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($w_thumbnail,$h_thumbnail); ?>" width="<?php echo $w_thumbnail;?>" height="<?php echo $h_thumbnail;?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
										</span>
										<span class="product-image image-rotator images-hover">
											<?php 
											$product = $_product;
											if ($product->getRotatorImage() && $product->getRotatorImage() !='no_selection') {
												//$imageTooltipResize = $this->getResizedUrl($imagetTooltip,600,400);
												$image = Mage::helper('catalog/image')->init($product, 'rotator_image')->resize($w_thumbnail,$h_thumbnail);
											?>
											<img src="<?php echo $image ?>" width="<?php echo $w_thumbnail;?>" height="<?php echo $h_thumbnail;?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
											<?php } ?>
										 </span>			
									</a>
								</div>
									 <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h2>
									<?php if($this->getConfig('review')) echo $this->getReviewsSummaryHtml($_product, 'short') ?>
							</div>
							<?php if( $this->getConfig('show_price') ): ?>
								<?php echo $this->getPriceHtml($_product, true) ?>
							<?php endif; ?>
							<div class="right-timer">
							<div class="actions">
									<div class="actions-inner">
									<?php if ($this->getConfig('addtocart')) { ?>
												<?php if($_product->isSaleable()): ?>
													<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><i class="fa fa-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></span></span></button>
												<?php else: ?>
													<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
												<?php endif; ?>
											<?php }?>
									<?php if( $this->getConfig('addtowishlist') || $this->getConfig('addtocompare') || $this->getConfig('review') ){?>
										<ul class="add-to-links">
										<?php if( $this->getConfig('addtowishlist')): ?>
											<?php if ($this->helper('wishlist')->isAllow()) : ?>
											<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><i class="fa fa-heart"></i><?php echo $this->__('Add to Wishlist') ?></a></li>
											<?php endif; ?>
										<?php endif; ?>
										<?php if( $this->getConfig('addtocompare')): ?>
											<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
											<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><i class="fa fa-retweet"></i><?php echo $this->__('Add to Compare') ?></a></li>
											<?php endif; ?>
										<?php endif; ?>
																<?php if($this->getConfig('review')): ?>				<?php endif; ?>
										</ul>
									<?php }?>
									</div>
								</div>
								<div class="box-timer">
										<?php if($timer_active == 1) :?>
										<?php if(($_product->getPrice() > $_product->getSpecialPrice() || $_product->getTypeID() == 'bundle') && $_product->getTimershow() == 1) : ?>
										<?php if($_product->getSpecialPrice()!= 0 || $_product->getSpecialPrice()!= "" ) :?>
										<?php if($timer_head_active == 'showall' || $timer_head_active == 'listpage' && $timer_head_active!='hideall' && $timer_head!= '') : ?>
																<div id="heading<?php echo $count; ?>"><?php echo $timer_head ?></div>
										<?php endif; ?>
																<div class="countbox_<?php echo $count; ?> timer-grid"></div>
										<?php if($timer_desc_active == 'showall' || $timer_desc_active == 'listpage' && $timer_desc_active!='hideall') : ?>
																
																<?php
																if($_product->getTypeID() == 'bundle')
																{
																	echo '<br/><h1 style="color:red">Discount up to '.(100 - $_product->getSpecialPrice()*1).'% </h1>';
																}
																?>
																<?php $count = $count + 1; ?>
										<?php endif;endif;endif;endif; ?>
									</div>
									</div>
						</div>
					</div>
					
                                  
                                    <?php if( $this->getConfig('description')){?>
                                        <div class="ma-desc">
                                            <?php if(!$this->getConfig('maxlength')){?>
                                                <?php echo nl2br($this->htmlEscape($_product->getShortDescription())) ?>
                                            <?php } else {?>
                                                <?php echo nl2br($this->cut_string_timer($this->htmlEscape($_product->getShortDescription()),$this->getConfig('maxlength'))) ?>			            
                                            <?php }?>			                    
                                        </div>
                                    <?php }?>
								</div>
						<?php $i++; ?>
						<?php if($i %$rows == 0) echo "</li>"; ?>  
						<?php if($_collectionSize == $i && $i % $rows != 0) echo "</li>"; ?>
					<?php endforeach; ?>		
				</ul>
				
				<?php $count = 1; ?>
				<?php $_collectionSize = $_productCollection->count() ?>
					<?php $i=0; foreach ($_productCollection as $_product): ?>
					<?php $toDate = $_product->getSpecialTODate();?>
					<?php $fromDate = $_product->getSpecialFromDate(); ?>
					<!--Condition for Timer Controllers goes here-->
					<?php if($timer_active == 1) :?>
					<?php if(($_product->getPrice() > $_product->getSpecialPrice() || $_product->getTypeID() == 'bundle') && $_product->getTimershow() == 1) : ?>
					<?php if($_product->getSpecialPrice()!= 0 || $_product->getSpecialPrice()!= "" ) :?>
						<?php $_current_timer = time(); ?>
							<script type="text/javascript">
								var dthen<?php echo $count; ?> = new Date("<?php echo Date("m/d/y", strtotime($toDate)).' 11:59:00 PM'; ?>");
								start = "<?php echo Date("m/d/y h:i:s A", $_current_timer); ?>";
								start_date = Date.parse(start);
								var dnow<?php echo $count; ?> = new Date(start_date);
								if(CountStepper>0)
									ddiff= new Date((dnow<?php echo $count; ?>)-(dthen<?php echo $count; ?>));
								else
									ddiff = new Date((dthen<?php echo $count; ?>)-(dnow<?php echo $count; ?>));
								//gsecs<?php echo $count; ?> = Math.floor(ddiff.valueOf()/1000);
								<?php if(strtotime($fromDate) <= $_current_timer){ ?>
									gsecs<?php echo $count; ?> = Math.floor(ddiff.valueOf()/1000);
								<?php }else{ ?>
									gsecs<?php echo $count; ?> = -1;
								<?php } ?>

								var iid<?php echo $count; ?> = "countbox_<?php echo $count; ?>";
								CountBack_slider(gsecs<?php echo $count; ?>,"countbox_<?php echo $count; ?>", <?php echo $count; ?>);
								j_blog++;
							</script>
					<?php $count = $count + 1; ?>
					<?php endif;endif;endif; ?>
					<!-- -->
					<?php $i++; ?>
					<?php endforeach; ?>

                <script type="text/javascript">
					$jq(document).ready(function(){
					  $jq('.ma-timer-container .bxslider').bxSlider(
						{
						<?php if($this->getConfig('auto')) { ?>
						  auto: true,
						<?php } ?>
						  speed: <?php echo $this->getConfig('speed') ?>,
						  pause: <?php echo $this->getConfig('interval') ?>,			  
						  minSlides: 1,
						  slideMargin: 30,
						  maxSlides: <?php echo $this->getConfig('items_show') ?>,
						  slideWidth: <?php echo $this->getConfig('item_width') ?>,
						<?php if ($this->getConfig('nav_ctrl')) { ?>
						  pager: true,
						<?php } else { ?> 
						  pager:false, 
						<?php } ?>
						<?php if ($this->getConfig('next_back')) { ?>
							controls: true,
						<?php } else { ?>
							controls:false,
						<?php } ?>
						 infiniteLoop:false,
						}
					  );
					});
				</script>
		<?php endif; ?> 
	</div> 
<?php } ?>