<div class="catlist">
	<div class="catlist-title title">
		<h2><?php echo $this->getListCfg('title')?></h2>
	</div>
	 
	<?php

	$catListTop = $this->getCatListTop();

	$i = 0;
	$j = 0;
	$last = count($catListTop);
	foreach ($catListTop as $catTop) {
		$j++;
		if($j%3 == 1) echo "<div class='row'>";
		if($i < $last) echo '<div class="col-xs-12 col-md-4 col-sm-12"><div class="catgrid">';
		else echo '<div class="col-xs-12 col-md-4 col-sm-12"><div class="catgrid last">';

	    	echo '<div class="catlist_level_top"><h3>'
		                .$catTop->getName()
		                .'</h3>';

	   
	    $CatList = $this->getCatByPath($catTop->getEntityId(), $catTop->getPath());
	    
	    $i = 0;
	    echo '<ul>';
	    foreach ($CatList as $cat) {
	      if($i >= $this->getListCfg('number_items')) break;
	        echo '<li><a href="' . Mage::getUrl($cat->getUrlPath()). '">'.$cat->getName().'</a></li>';
	        $i++;
	    }
	    echo '</ul></div>';
		echo '<div class="cat_image"><a href="' . Mage::getUrl($catTop->getUrlPath()). '">' 
		                    .'<img src="'.$this->getImage($catTop).'" alt="'.$catTop->getName().'" />
		                </a></div>';
		echo '</div></div>';
		if($j%3 == 0) echo "</div>";
	    $i++; // not trung voi $i o tren
	}
	?>

</div>